// Factory addresses deployed on different chains
export const CONTRACTS = {
  L1_TOKEN_FACTORY: {
    address: '0xf87eA3325c6F5Be2119D40747752BB255CdF1eE8',
    chainId: 11155111, // Sepolia
    name: 'L1TokenFactory',
  },
  L2_SUPERCHAIN_TOKEN_FACTORY: {
    address: '0xda572dDA586970a0b844d2E7a2e55fe3af35b225',
    chainId: 11142220, // Celo Sepolia (Alfajores)
    name: 'L2SuperChainTokenFactory',
  },
} as const;

// Backend API URL for promo codes
export const PROMO_API_URL = import.meta.env.VITE_PROMO_API_URL || 'http://localhost:3001';

// ABI for L1TokenFactory
export const L1_TOKEN_FACTORY_ABI = [
  {
    name: 'createToken',
    type: 'function',
    inputs: [
      { name: 'name_', type: 'string' },
      { name: 'symbol_', type: 'string' },
      { name: 'initialSupply_', type: 'uint256' },
      { name: 'maxSupply_', type: 'uint256' },
      { name: 'decimals_', type: 'uint8' },
      { name: 'owner_', type: 'address' },
    ],
    outputs: [{ name: 'tokenAddress', type: 'address' }],
    stateMutability: 'payable',
  },
  {
    name: 'createTokenWithPromo',
    type: 'function',
    inputs: [
      { name: 'name_', type: 'string' },
      { name: 'symbol_', type: 'string' },
      { name: 'initialSupply_', type: 'uint256' },
      { name: 'maxSupply_', type: 'uint256' },
      { name: 'decimals_', type: 'uint8' },
      { name: 'owner_', type: 'address' },
      { name: 'promoFee_', type: 'uint256' },
      { name: 'promoNonce_', type: 'bytes32' },
      { name: 'expiresAt_', type: 'uint256' },
      { name: 'signature_', type: 'bytes' },
    ],
    outputs: [{ name: 'tokenAddress', type: 'address' }],
    stateMutability: 'payable',
  },
  {
    name: 'creationFee',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'TokenCreated',
    type: 'event',
    inputs: [
      { name: 'tokenAddress', type: 'address', indexed: true },
      { name: 'name', type: 'string' },
      { name: 'symbol', type: 'string' },
      { name: 'initialSupply', type: 'uint256' },
      { name: 'maxSupply', type: 'uint256' },
      { name: 'decimals', type: 'uint8' },
      { name: 'owner', type: 'address', indexed: true },
    ],
  },
  {
    name: 'getAllTokens',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'address[]' }],
    stateMutability: 'view',
  },
  {
    name: 'getAllTokensCount',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
] as const;

// ABI for L1Token
export const L1_TOKEN_ABI = [
  {
    name: 'name',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'string' }],
    stateMutability: 'view',
  },
  {
    name: 'symbol',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'string' }],
    stateMutability: 'view',
  },
  {
    name: 'decimals',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    name: 'totalSupply',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'balanceOf',
    type: 'function',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'maxSupply',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'owner',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    name: 'paused',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    name: 'mint',
    type: 'function',
    inputs: [
      { name: 'to_', type: 'address' },
      { name: 'amount_', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'burn',
    type: 'function',
    inputs: [
      { name: 'from_', type: 'address' },
      { name: 'amount_', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'transfer',
    type: 'function',
    inputs: [
      { name: 'to_', type: 'address' },
      { name: 'amount_', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    name: 'pause',
    type: 'function',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'unpause',
    type: 'function',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'setMaxSupply',
    type: 'function',
    inputs: [{ name: 'newMaxSupply', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'setRemoteToken',
    type: 'function',
    inputs: [{ name: '_remoteToken', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'setBridge',
    type: 'function',
    inputs: [{ name: '_bridge', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'MaxSupplyUpdated',
    type: 'event',
    inputs: [{ name: 'newMaxSupply', type: 'uint256', indexed: false }],
  },
] as const;

// ABI for L2SuperChainTokenFactory
export const L2_SUPERCHAIN_TOKEN_FACTORY_ABI = [
  {
    name: 'createToken',
    type: 'function',
    inputs: [
      { name: 'owner_', type: 'address' },
      { name: 'name_', type: 'string' },
      { name: 'symbol_', type: 'string' },
      { name: 'decimals_', type: 'uint8' },
      { name: 'initialSupply_', type: 'uint256' },
      { name: 'maxSupply_', type: 'uint256' },
      { name: 'salt_', type: 'bytes' },
    ],
    outputs: [{ name: 'tokenAddress', type: 'address' }],
    stateMutability: 'payable',
  },
  {
    name: 'createTokenWithBridge',
    type: 'function',
    inputs: [
      { name: 'owner_', type: 'address' },
      { name: 'name_', type: 'string' },
      { name: 'symbol_', type: 'string' },
      { name: 'decimals_', type: 'uint8' },
      { name: 'initialSupply_', type: 'uint256' },
      { name: 'maxSupply_', type: 'uint256' },
      { name: 'bridge_', type: 'address' },
      { name: 'remoteToken_', type: 'address' },
      { name: 'salt_', type: 'bytes' },
    ],
    outputs: [{ name: 'tokenAddress', type: 'address' }],
    stateMutability: 'nonpayable',
  },
  {
    name: 'createTokenWithPromo',
    type: 'function',
    inputs: [
      { name: 'owner_', type: 'address' },
      { name: 'name_', type: 'string' },
      { name: 'symbol_', type: 'string' },
      { name: 'decimals_', type: 'uint8' },
      { name: 'initialSupply_', type: 'uint256' },
      { name: 'maxSupply_', type: 'uint256' },
      { name: 'salt_', type: 'bytes' },
      { name: 'promoFee_', type: 'uint256' },
      { name: 'promoNonce_', type: 'bytes32' },
      { name: 'expiresAt_', type: 'uint256' },
      { name: 'signature_', type: 'bytes' },
    ],
    outputs: [{ name: 'tokenAddress', type: 'address' }],
    stateMutability: 'payable',
  },
  {
    name: 'creationFee',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'TokenCreated',
    type: 'event',
    inputs: [
      { name: 'tokenAddress', type: 'address', indexed: true },
      { name: 'name', type: 'string' },
      { name: 'symbol', type: 'string' },
      { name: 'decimals', type: 'uint8' },
      { name: 'initialSupply', type: 'uint256' },
      { name: 'maxSupply', type: 'uint256' },
      { name: 'owner', type: 'address', indexed: true },
    ],
  },
  {
    name: 'getAllTokens',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'address[]' }],
    stateMutability: 'view',
  },
  {
    name: 'getAllTokensCount',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
] as const;

// ABI for L2SuperChainToken
export const L2_SUPERCHAIN_TOKEN_ABI = [
  {
    name: 'name',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'string' }],
    stateMutability: 'view',
  },
  {
    name: 'symbol',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'string' }],
    stateMutability: 'view',
  },
  {
    name: 'decimals',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    name: 'totalSupply',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'balanceOf',
    type: 'function',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'maxSupply',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    name: 'owner',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    name: 'paused',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    name: 'REMOTE_TOKEN',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    name: 'BRIDGE',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    name: 'remoteToken',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    name: 'bridge',
    type: 'function',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
    stateMutability: 'view',
  },
  {
    name: 'mint',
    type: 'function',
    inputs: [
      { name: 'to_', type: 'address' },
      { name: 'amount_', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'burn',
    type: 'function',
    inputs: [
      { name: 'from_', type: 'address' },
      { name: 'amount_', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'transfer',
    type: 'function',
    inputs: [
      { name: 'to_', type: 'address' },
      { name: 'amount_', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    name: 'pause',
    type: 'function',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'unpause',
    type: 'function',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'setMaxSupply',
    type: 'function',
    inputs: [{ name: 'newMaxSupply', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'setRemoteToken',
    type: 'function',
    inputs: [{ name: '_remoteToken', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'setBridge',
    type: 'function',
    inputs: [{ name: '_bridge', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    name: 'MaxSupplyUpdated',
    type: 'event',
    inputs: [{ name: 'newMaxSupply', type: 'uint256', indexed: false }],
  },
] as const;
