[profile.default]
src = "src"
out = "out"
ffi = true
ast = true
build_info = true
libs = ["lib"]
extra_output = ["storageLayout"]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


[etherscan]
celo = { key = "I36FHHV8SEQP38FSSMQUCI92BJK4H5PJSE" }
sepolia = { key = "I36FHHV8SEQP38FSSMQUCI92BJK4H5PJSE" }
celo-sepolia = { key = "I36FHHV8SEQP38FSSMQUCI92BJK4H5PJSE" }


[rpc_endpoints]
celo = "https://lb.drpc.org/ogrpc?network=celo&dkey=AnN38OUr3EcfnfM04Tc8vZSVaPnrRU8R8IlbKlzbRHZc"
celo-sepolia = "https://lb.drpc.live/celo-sepolia/AuajrTfUKUDcljFTxiXAxPOrBZbcQJQR8Jr2uuQ63qxe"
sepolia = "https://sepolia.drpc.org"
